### PR TITLE
d.ts t4 generator for application services

### PR DESCRIPTION
**Pull request by SlavaUtesinov**
## d.ts t4 generator for application services at case of angularjs

With it's help you can create d.ts definition file for all application services with fully described types and methods. 

Main differences with TypeScriptController mechanism:
1. all what is needed - just rebuild WebSpaAngular project and then Run t4 template, instead of calling /api/TypeScript url, copying and pasting it's response to project.
2. It is very simple to debug generator: you can create console application, add all necessary references and then call `TypeScriptGenerator.Start(Console.WriteLine);` instead of `TypeScriptGenerator.Start(WriteLine)` (actually, t4 template consists of the only one row, so it is not necessary to know t4 syntax)

For demonstration d.ts is already created, also nuget package jquery.TypeScript.DefinitelyTyped is added to supply JQueryAjaxSettings type.

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you very much. We will review it.

**Comment by ismcagdas** [comment]
Hi @SlavaUtesinov,

How do you use generated d.ts in your project, can you share an example ?
It will be better if you can send full source code with this type definition is used.

Thanks.

**Comment by SlavaUtesinov** [comment]
Hello, @ismcagdas.

At my project I use TypeScript, and as your framework contains _"dynamic api controllers as angularjs services"_, I thought, it will be very comfortable to also generate d.ts annotations for them and use it as **intellisense**. So, instead of looking for, what method's name and arguments should I use for particular service, I simply use _intellisense_'s help. For example, 'app.views.users.index' controller's code will look like:

sample

**Comment by ismcagdas** [comment]
Hi,

Thank you for your work but we decided not to include it to default template.
It currently uses JQueryAjaxSettings but it should use angular's default for this.

We will offer your work to use if anyone asks such a feature.

Thanks again for your work.

**Pull request closed without merging**
