### PR TITLE
fix #139 migration record errors.

### LINKED ISSUE #139: Migration error
About https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3732

https://github.com/aspnetboilerplate/module-zero-template/blob/master/src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/201807270535111_Updated_ABP.cs#L13

It recreated all the tables.

### PR DESCRIPTION
**Pull request by maliming**

### CODE REVIEW

**Comment by rqx110** [comment]
好像不能直接删除吧，因为有些列长度有修改，比如表dbo.AbpUsers的SecurityStamp做了128限制，表dbo.AbpAuditLogs的BrowserInfo长度由256增加到512了。

**Comment by maliming** [comment]
@rqx110 @alirizaadiyahsi 
When I tried to add a new migration, EF did not detect any changes, in fact the length of entities such as AbpAuditLogs has been modified.

If delete all migration records, re-creation will be correct.

**Comment by alirizaadiyahsi** [comment]
Hi @maliming, 

> If delete all migration records, re-creation will be correct.

This is better solution. You can remove all migrrations and add an "Initial_Migration" only. Then I wll merge it.

I mean just one migration something following:

image

**Comment by maliming** [comment]
Regenerated.

**Comment by alirizaadiyahsi** [comment]
Thanks @maliming

**Pull request merged**
