### PR TITLE
Change Password ViewModel, PartialView and AccountController methods

### PR DESCRIPTION
**Pull request by ddNils**
The ChangePassword View is designed to be loaded inside a modal popup. 

I went for this approach: http://www.codeproject.com/Tips/826002/Bootstrap-Modal-Dialog-Loading-Content-from-MVC-Pa 

But other implementations should be possible as well (including implementation with WebApi).

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you very much. I will review and merge your pull request :)

**Comment by hikalkan** [comment]
It seems you missed to add needed javascript code to open partialview in the modal (step 3 in http://www.codeproject.com/Tips/826002/Bootstrap-Modal-Dialog-Loading-Content-from-MVC-Pa).
So, it's not working.

**Comment by hikalkan** [comment]
Also, I think we should user Angular's $modal service (https://angular-ui.github.io/bootstrap/#/modal) instead of a custom MVC bootstrap modal implementation.

**Comment by ddNils** [comment]
Yes I was unsure where to add the script
Am 05.12.2015 20:25 schrieb "Halil İbrahim Kalkan" <notifications@github.com

**Pull request merged**
